### ISSUE TITLE
Why am I getting this issue

### ISSUE THREAD

**Issue by IgnacyFluder** [avilash/TikTokAPI-Python#25]
Traceback (most recent call last):
  File "c:/Users/48606/Desktop/ttbot/skrypt.py", line 26, in <module>
    api.downloadVideoById(trendin[i], 'C:\\Users\\48606\\Desktop\\ttbot\\vids_tmp')
  File "C:\Users\48606\AppData\Local\Programs\Python\Python37\lib\site-packages\TikTokAPI\tiktokapi.py", line 242, in downloadVideoById
    with open(save_path, 'wb') as f:
PermissionError: [Errno 13] Permission denied: 'C:\\Users\\48606\\Desktop\\ttbot\\vids_tmp'

I have the newest version

**Comment by ivall** [comment]
Run it as administrator.

**Comment by IgnacyFluder** [comment]
for anyone who has this issue.
You need to type the file too.
example'C:\Users\48606\Desktop\ttbot\vids_tmp\video.mp4'
