### ISSUE TITLE
I got Installation error

### ISSUE THREAD

**Issue by qlchen1** [avilash/TikTokAPI-Python#62]
Can you help? Did i miss some other packages? 

ERROR: Command errored out with exit status 1:
     command: 'c:\python27\python.exe' -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'c:\\users\\xiaoto~1\\appdata\\local\\temp\\pip-install-ih5dkv\\tiktokapi\\setup.py'"'"'; __file__='"'"'c:\\users\\xiaoto~1\\appdata\\local\\temp\\pip-install-ih5dkv\\tiktokapi\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base 'c:\users\xiaoto~1\appdata\local\temp\pip-pip-egg-info-oroizo'
         cwd: c:\users\xiaoto~1\appdata\local\temp\pip-install-ih5dkv\tiktokapi\
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "c:\users\xiaoto~1\appdata\local\temp\pip-install-ih5dkv\tiktokapi\setup.py", line 5, in <module>
        with open("README.md", "r", encoding="utf-8") as fh:
    TypeError: 'encoding' is an invalid keyword argument for this function
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

**Comment by qlchen1** [comment]
I upgraded python. Got this resolved.
